### ISSUE TITLE
FYI: Snap - Kernel 6.0 Bug

### ISSUE THREAD

**Issue by juvtib** [PowerShell/PowerShell-Snap#93] opened 2022-10-15 22:39 UTC
After a few hours of using the PowerShell snap with a 6.0 kernel, new shells cannot be opened with the following error: 

```
pwsh: /snap/core20/current/lib/x86_64-linux-gnu/libdl.so.2: unsupported version 
0 of Verdef record
pwsh: error while loading shared libraries: /snap/core20/current/lib/x86_64-linu
x-gnu/libdl.so.2: unsupported version 0 of Verneed record

```

I found a kernel thread that seems related. 

* [Re: BISECT result: 6.0.0-RC kernels trigger Firefox snap bug with 6.0.0-rc3 through 6.0.0-rc7 - Phillip Lougher](https://lore.kernel.org/lkml/20221015205936.5735-1-phillip@squashfs.org.uk/)

Right now, it seems like we need to wait for the underlying kernel bug to be addressed. 

My advice is to roll back to your last kernel: 5.19 or earlier. Someone also said rebooting temporarily fixes the issue. 

## Related
* [Kernel 6.0.0 triggers snap bug with LXD on ubuntu 22.04.1 · Issue PowerShell/PowerShell#11005 · lxc/lxd · GitHub](https://github.com/lxc/lxd/issues/11005)
* [Unsupported version 0 of Verneed record Linux 6.0 - snapd - snapcraft.io](https://forum.snapcraft.io/t/unsupported-version-0-of-verneed-record-linux-6-0/32160)
* [Re: 6.0.0-RC kernels trigger Firefox snap bug with 6.0.0-rc3 through 6.0.0-rc7 - Thorsten Leemhuis](https://lore.kernel.org/lkml/5bb75cbc-a0db-537b-12d0-889230c865d8@leemhuis.info/)
* [Manjaro Kernel Activity](https://gitlab.manjaro.org/packages/core/linux60/activity)

Regards,

**Comment by TravisEz13** [comment] 2022-10-31 20:17
The issue is in the core20 layer which Canonical owns.  Resolving external as we wait for the fix.

**Closed by TravisEz13** 2022-10-31 20:17 UTC
Labels: Resolution-External

**Comment by juvtib** [comment] 2022-11-01 04:40
For those who are interested, the patch series is here: 

* [\[0/3\] squashfs: fix some regressions introduced in the readahead code - Phillip Lougher](https://lore.kernel.org/lkml/20221020223616.7571-1-phillip@squashfs.org.uk/)

This is reported as solving the snap bug.

**Comment by diddledani** [comment] 2022-11-01 16:02
This is, as you found via the LKML, a regression in the squashfs code within Linux 6.0. It affects any system using Linux 6.0 and is not specific to snaps or the PowerShell snap specifically.

**Comment by juvtib** [comment] 2022-11-05 07:12
It looks like the fix for snaps will make it into Linux kernel v6.0.7 

* [\[PATCH 6.0 000/240\] 6.0.7-rc1 review - Greg Kroah-Hartman](https://lore.kernel.org/lkml/20221102022111.398283374@linuxfoundation.org/)

``` text
Phillip Lougher <phillip@squashfs.org.uk>
    squashfs: fix buffer release race condition in readahead code

Phillip Lougher <phillip@squashfs.org.uk>
    squashfs: fix extending readahead beyond end of file

Phillip Lougher <phillip@squashfs.org.uk>
    squashfs: fix read regression introduced in readahead code

```

**Comment by diddledani** [comment] 2022-11-05 10:38
it did make it to 6.0.7, which was released on the 3rd of November 2022.
