### ISSUE TITLE
Unable to install modules from Powershell installed via snap

### ISSUE THREAD

**Issue by JeffLabonte** [PowerShell/PowerShell-Snap#23] opened 2019-01-30 02:01 UTC
# Steps to reproduce

```powershell

Install-Module posh-git -Scope CurrentUser -AllowPrerelease -Force 

```

# Expected behavior

```
Install the module posh-git
```

# Actual behavior

```
PackageManagement\Install-Package : No match was found for the specified search criteria and module name 'posh-git'. Try Get-PSRepository to see all available registered module repositories.
At /var/lib/snapd/snap/powershell/17/opt/powershell/Modules/PowerShellGet/PSModule.psm1:9491 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
+ FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```

# Additional Data
```
> Get-PSRepository                                                  
OUTPUT :
WARNING: Unable to find module repositories.


> Get-PSRepository                                                  
WARNING: Unable to find module repositories.

```

# Environment data

```
Name                           Value
----                           -----
PSVersion                      6.1.2
PSEdition                      Core
GitCommitId                    6.1.2
OS                             Linux 4.20.4-arch1-1-ARCH #1 SMP PREEMPT Wed Jan 23 00:12:22 UTC 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


```

**Comment by NetDevAutomate** [comment] 2019-12-01 18:00
Seems the issue is still present. Uninstalled and installed with yum, the issue has now gone.

**Comment by TravisEz13** [comment] 2020-03-05 21:45
Requested information for troubleshooting has not been supplied for over a year.  Closing the issue.

**Closed by TravisEz13** 2020-03-05 21:45 UTC
Labels: Issue-Question
